name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Kodni klonlash
        uses: actions/checkout@v4

      - name: Node.js o‘rnatish
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Serverga ulanish va yangilash
        run: |
          ssh user@server_ip "cd test && git pull && pm2 restart test"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
