name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Kodni klonlash
        uses: actions/checkout@v4

      - name: Node.js o‘rnatish
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: SSH kalitlarni sozlash
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_actions_key
          chmod 600 ~/.ssh/github_actions_key
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Serverga ulanish va yangilash
        run: |
          ssh ${{ secrets.SERVER_NAME }}@${{ secrets.SERVER_IP }} "cd test && git stash && git pull && npm install && npm run build && pm2 restart test"
